# Generated by Django 2.0.2 on 2018-04-20 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bacterium_type', models.CharField(choices=[('ANAEROBIC', 'anaerobic'), ('AEROBIC', 'aerobic')], max_length=12)),
                ('ideal_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ideal_humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ideal_acidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ideal_oxygen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=30)),
                ('experiment_temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('experiment_humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('experiment_acidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('experiment_oxygen', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('bacterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Bacterium')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theimage', models.ImageField(null=True, upload_to='img')),
                ('from_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Experiment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together={('bacterium', 'name')},
        ),
    ]
