# Generated by Django 2.0.2 on 2018-04-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bacterium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('baterium_type', models.CharField(choices=[('ANAEROBIC', 'anaerobic'), ('AEROBIC', 'aerobic')], max_length=12)),
                ('ideal_temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ideal_humidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ideal_acidity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('ideal_oxygen', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=30)),
                ('experiment_temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('experiment_humidity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('experiment_acidity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('experiment_oxygen', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
                ('bacterium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.Bacterium')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='A label for URL config', max_length=30, unique=True)),
                ('mad_experiments', models.ManyToManyField(to='laboratory.Experiment')),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='experiment',
            unique_together={('bacterium', 'name')},
        ),
    ]
