# Generated by Django 2.0.2 on 2018-04-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacterium',
            old_name='baterium_type',
            new_name='bacterium_type',
        ),
        migrations.AlterField(
            model_name='bacterium',
            name='ideal_acidity',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
